# Generated by Django 2.1 on 2018-08-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imageCover',
            field=models.FileField(default='documents/default.png', upload_to='documents/'),
        ),
    ]
