# Generated by Django 2.1 on 2018-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_imagecover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imageCover',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
