# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20180826_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='albums.Album'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='albums.Album'),
        ),
        migrations.AlterField(
            model_name='title',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='albums.Album'),
        ),
        migrations.AlterField(
            model_name='title',
            name='duration',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
