# Generated by Django 2.1 on 2018-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20180828_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imageCover',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
