# Generated by Django 2.1 on 2018-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20180828_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imageCover',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
